// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-congregations.ts
import { createClient } from "npm:@supabase/supabase-js@^2.57.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_congregations_default = defineTool({
  name: "list_congregations",
  title: "List congregations",
  description: "List EBD congregations the signed-in user has access to. Returns id, name, headquarters_id, regional_id, is_headquarters.",
  inputSchema: {
    search: z.string().optional().describe("Optional case-insensitive substring to match in the congregation name."),
    limit: z.number().int().min(1).max(200).optional().describe("Max rows to return (default 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser(ctx).from("congregations").select("id,name,headquarters_id,regional_id,is_headquarters").order("name", { ascending: true }).limit(limit ?? 100);
    if (search && search.trim()) q = q.ilike("name", `%${search.trim()}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { congregations: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-classes.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.57.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_classes_default = defineTool2({
  name: "list_classes",
  title: "List classes",
  description: "List EBD classes the signed-in user can see. Optionally filter by congregation_id.",
  inputSchema: {
    congregation_id: z2.string().uuid().optional().describe("Filter classes by congregation UUID."),
    limit: z2.number().int().min(1).max(500).optional().describe("Max rows to return (default 200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ congregation_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser2(ctx).from("classes").select("id,name,congregation_id,teacher_student_id").order("name", { ascending: true }).limit(limit ?? 200);
    if (congregation_id) q = q.eq("congregation_id", congregation_id);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { classes: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-students.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.57.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_students_default = defineTool3({
  name: "list_students",
  title: "List students",
  description: "List students the signed-in user can see. Filter by class_id and/or active status.",
  inputSchema: {
    class_id: z3.number().int().optional().describe("Filter students by class id."),
    active_only: z3.boolean().optional().describe("Only return active students (default true)."),
    search: z3.string().optional().describe("Optional case-insensitive substring to match in the student's name."),
    limit: z3.number().int().min(1).max(500).optional().describe("Max rows to return (default 200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ class_id, active_only, search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser3(ctx).from("students").select("id,name,class_id,active,cargo,phone,birth_date").order("name", { ascending: true }).limit(limit ?? 200);
    if (typeof class_id === "number") q = q.eq("class_id", class_id);
    if (active_only !== false) q = q.eq("active", true);
    if (search && search.trim()) q = q.ilike("name", `%${search.trim()}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { students: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-recent-registrations.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.57.2";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_recent_registrations_default = defineTool4({
  name: "list_recent_registrations",
  title: "List recent EBD registrations",
  description: "List recent EBD class registrations (attendance + offerings) visible to the signed-in user. Optionally filter by class_id and date range (YYYY-MM-DD).",
  inputSchema: {
    class_id: z4.number().int().optional().describe("Filter by class id."),
    since: z4.string().optional().describe("Include registrations on or after this date (YYYY-MM-DD)."),
    until: z4.string().optional().describe("Include registrations on or before this date (YYYY-MM-DD)."),
    limit: z4.number().int().min(1).max(200).optional().describe("Max rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ class_id, since, until, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser4(ctx).from("registrations").select(
      "id,class_id,registration_date,total_present,visitors,bibles,magazines,offering_cash,offering_pix,hymn,ebd_notes,class_notes,reconciled,created_at"
    ).order("registration_date", { ascending: false }).limit(limit ?? 50);
    if (typeof class_id === "number") q = q.eq("class_id", class_id);
    if (since) q = q.gte("registration_date", since);
    if (until) q = q.lte("registration_date", until);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { registrations: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "fotzydevyvvklalgsomf";
var mcp_default = defineMcp({
  name: "ebd-system-pro-mcp",
  title: "EBD System Pro",
  version: "0.1.0",
  instructions: "Tools to read EBD (Escola B\xEDblica Dominical) data from this app: congregations, classes, students, and weekly registrations. All access respects the signed-in user's hierarchy (master, igreja_m\xE3e, igreja_sede, admin_regional, secret\xE1rio_ebd, professor_classe).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_congregations_default, list_classes_default, list_students_default, list_recent_registrations_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
